GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO PUBLIC;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id          serial,
  user_name  varchar
);
